image:
  tag: main
ingress:
  hosts:
    - host: pbotapps-test.portland.gov
      paths:
        - path: /parking
          pathType: Prefix
  tls:
    - secretName: pbotapps-test-portland-gov-tls
      hosts:
        - pbotapps-test.portland.gov
